notables

plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.5)           )
plotfir.plot_firwin(window= ('tukey',0.3)                        )
plotfir.plot_remez(t_width = 70) # width like firwin('invendelirium1', 0.2, 0.5)
plotfir.plot_firls(t_width = 30) # width like firwin('invendelirium1', 0.2, 0.5)

all

plotfir.plot_firwin(window= ('barthann')                         )
plotfir.save()
plotfir.plot_firwin(window= ('bartlett')                         )
plotfir.save()
plotfir.plot_firwin(window= ('blackman')                         )
plotfir.save()
plotfir.plot_firwin(window= ('blackmanharris')                   )
plotfir.save()
plotfir.plot_firwin(window= ('bohman')                           )
plotfir.save()
plotfir.plot_firwin(window= ('boxcar')                           )
plotfir.save()
plotfir.plot_firwin(window= ('chebwin',45)                       )
plotfir.plot_firwin(window= ('chebwin',80)                       )
plotfir.save()
plotfir.plot_firwin(window= ('dpss',0.2)                         )
plotfir.plot_firwin(window= ('dpss',0.02)                        )
plotfir.save()
plotfir.plot_firwin(window= ('exponential', None, 200)           )
plotfir.save()
plotfir.plot_firwin(window= ('flattop')                          )
plotfir.save()
plotfir.plot_firwin(window= ('gaussian',0.1*731)                 )
plotfir.plot_firwin(window= ('gaussian',0.3*731)                 )
plotfir.plot_firwin(window= ('gaussian',1.0*731)                 )
plotfir.save()
plotfir.plot_firwin(window= ('hamming')                          )
plotfir.save()
plotfir.plot_firwin(window= ('hann')                             )
plotfir.save()
plotfir.plot_firwin(window= ('kaiser',2)                         )
plotfir.plot_firwin(window= ('kaiser',14)                        )
plotfir.save()
plotfir.plot_firwin(window= ('nuttall')                          )
plotfir.save()
plotfir.plot_firwin(window= ('parzen')                           )
plotfir.save()
plotfir.plot_firwin(window= ('slepian',0.02)                     )
plotfir.plot_firwin(window= ('slepian',0.01)                     )
plotfir.save()
plotfir.plot_firwin(window= ('triang')                           )
plotfir.save()
plotfir.plot_firwin(window= ('tukey',0.3)                       )
plotfir.plot_firwin(window= ('tukey',0.5)                        )
plotfir.plot_firwin(window= ('tukey',0.7)                          )
plotfir.save()
plotfir.plot_firwin(window= ('invendelirium1', 0.5, 1)           )
plotfir.save()
plotfir.plot_firwin(window= ('invendelirium1dip', 0.5, 1, 4)     )
plotfir.save()

plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.3)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.4)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.5)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.6)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.7)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.8)           )
plotfir.plot_firwin(window= ('tukey',0.5)                        )


plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.5)           )
plotfir.plot_firwin(window= ('tukey',0.2)                        )
plotfir.plot_firwin(window= ('tukey',0.3)                        )
plotfir.plot_firwin(window= ('tukey',0.4)                        )
plotfir.plot_firwin(window= ('tukey',0.5)                        )
plotfir.plot_firwin(window= ('tukey',0.6)                        )
plotfir.plot_firwin(window= ('tukey',0.7)                        )

plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.5)           )
plotfir.plot_firwin(window= ('tukey',0.3)                        )

plotfir.plot_firwin(window= ('invendelirium1', 0.1, 0.5)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.5)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.3, 0.5)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.4, 0.5)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.5, 0.5)           )

plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.3)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.4)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.5)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.6)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.7)           )

plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 0)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 1)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 2)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 3)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 4)           )


plotfir.plot_firwin(window= ('invendelirium1dip', 0.1, 0.5, 2)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 2)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.3, 0.5, 2)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.4, 0.5, 2)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.5, 0.5, 2)           )

plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.1, 4)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.3, 4)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.5, 4)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.7, 4)           )
plotfir.plot_firwin(window= ('invendelirium1dip', 0.2, 0.9, 4)           )

plotfir.plot_firwin(window= ('invendelirium1dip', 0.4, 0.5, 2)           )
plotfir.plot_firwin(window= ('invendelirium1', 0.2, 0.5)           )
